export const SET_PASSWORD = "SET_PASSWORD";
export const SET_BACK_BUTTON = "SET_BACK_BUTTON";

export const GET_USER_PROFILE_PENDING = 'GET_USER_PROFILE';
// get user list - success
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
// get user list - failure
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const GET_USER_LOGIN_PENDING = 'GET_USER_LOGIN_PENDING';
// get login list - success
export const GET_USER_LOGIN_SUCCESS = 'GET_USER_LOGIN_SUCCESS';
// get login list - failure
export const GET_USER_LOGIN_FAILURE = 'GET_USER_LOGIN_FAILURE';

export const GET_USER_BIDDING_PENDING = 'GET_USER_BIDDING_PENDING';
// get bidding list - success
export const GET_USER_BIDDING_SUCCESS = 'GET_USER_BIDDING_SUCCESS';
// get bidding list - failure
export const GET_USER_BIDDING_FAILURE = 'GET_USER_BIDDING_FAILURE';

export const GET_USER_BILLING_PENDING = 'GET_USER_BILLING_PENDING';
// get billing list - success
export const GET_USER_BILLING_SUCCESS = 'GET_USER_BILLING_SUCCESS';
// get billing list - failure
export const GET_USER_BILLING_FAILURE = 'GET_USER_BILLING_FAILURE';

export const LOGIN_AUTHENTIFICATION_PENDING = 'LOGIN_AUTHENTIFICATION_PENDING';
// get billing list - success
export const LOGIN_AUTHENTIFICATION_SUCCESS = 'LOGIN_AUTHENTIFICATION_SUCCESS';
// get billing list - failure
export const LOGIN_AUTHENTIFICATION_FAILURE = 'LOGIN_AUTHENTIFICATION_FAILURE';

export const USER_CHECKIN_STATUS = "USER_CHECKIN_STATUS";

export const PROJECT_TIMER_UPDATE = "PROJECT_TIMER_UPDATE";

export const ATTENDANCE = "ATTENDANCE";

export const ATTENDANCEERROR = "ATTENDANCEERROR"

export const PROJECTCHECKOUT = "PROJECTCHECKOUT"

export const PROJECTCHECKOUTERROR = "PROJECTCHECKOUTERROR"

export const STOPTIMER = "STOPTIMER"

export const STOPTIMERERROR = "STOPTIMERERROR"